# Theme settings
doks:
    baseurl:
    color_theme: yellow # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: Damien Irving
            image:
        nav:
            - item_name: Story
              item_url: '/story'
            - item_name: Experience
              item_url: '/experience'
            - item_name: Publications
              item_url: '/packages'
    footer:
        content:
            logo:
                text: Damien Irving
                image:
            copyright:
        social_list:
            - network_name: twitter
              profile_url: 'https://twitter.com/DrClimate'
            - network_name: github
              profile_url: 'https://github.com/DamienIrving'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
